<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="7" total="20" passed="13">
  <reporter-output>
  </reporter-output>
  <suite name="Test2 - Suite" duration-ms="3310" started-at="2016-11-01T18:36:50Z" finished-at="2016-11-01T18:36:53Z">
    <groups>
    </groups>
    <test name="ApiTest" duration-ms="3310" started-at="2016-11-01T18:36:50Z" finished-at="2016-11-01T18:36:53Z">
      <class name="automationFramework.TestCases.ApiCustomerPost">
        <test-method status="PASS" signature="setUp()[pri:0, instance:automationFramework.TestCases.ApiCustomerPost@eec5a4a]" name="setUp" is-config="true" duration-ms="557" started-at="2016-11-01T11:36:50Z" finished-at="2016-11-01T11:36:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="apiErrorAddressId()[pri:0, instance:automationFramework.TestCases.ApiCustomerPost@eec5a4a]" name="apiErrorAddressId" duration-ms="1592" started-at="2016-11-01T11:36:50Z" finished-at="2016-11-01T11:36:52Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at automationFramework.TestCases.ApiCustomerPost.checkError(ApiCustomerPost.java:372)
	at automationFramework.TestCases.ApiCustomerPost.apiErrorAddressId(ApiCustomerPost.java:187)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:177)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:105)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:103)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:74)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- apiErrorAddressId -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:automationFramework.TestCases.ApiCustomerPost@eec5a4a]" name="setUp" is-config="true" duration-ms="15" started-at="2016-11-01T11:36:52Z" finished-at="2016-11-01T11:36:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="apiErrorBlankAddress()[pri:0, instance:automationFramework.TestCases.ApiCustomerPost@eec5a4a]" name="apiErrorBlankAddress" duration-ms="43" started-at="2016-11-01T11:36:52Z" finished-at="2016-11-01T11:36:52Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [If address is provided, address1 is required.] but found [Field is blank.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [If address is provided, address1 is required.] but found [Field is blank.]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at automationFramework.TestCases.ApiCustomerPost.checkError(ApiCustomerPost.java:374)
	at automationFramework.TestCases.ApiCustomerPost.apiErrorBlankAddress(ApiCustomerPost.java:198)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:177)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:105)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:103)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:74)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- apiErrorBlankAddress -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:automationFramework.TestCases.ApiCustomerPost@eec5a4a]" name="setUp" is-config="true" duration-ms="16" started-at="2016-11-01T11:36:52Z" finished-at="2016-11-01T11:36:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="apiErrorBlankCity()[pri:0, instance:automationFramework.TestCases.ApiCustomerPost@eec5a4a]" name="apiErrorBlankCity" duration-ms="31" started-at="2016-11-01T11:36:52Z" finished-at="2016-11-01T11:36:52Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [If address is provided, city is required.] but found [Field is blank.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [If address is provided, city is required.] but found [Field is blank.]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at automationFramework.TestCases.ApiCustomerPost.checkError(ApiCustomerPost.java:374)
	at automationFramework.TestCases.ApiCustomerPost.apiErrorBlankCity(ApiCustomerPost.java:233)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:177)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:105)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:103)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:74)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- apiErrorBlankCity -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:automationFramework.TestCases.ApiCustomerPost@eec5a4a]" name="setUp" is-config="true" duration-ms="22" started-at="2016-11-01T11:36:52Z" finished-at="2016-11-01T11:36:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="apiErrorBlankContact()[pri:0, instance:automationFramework.TestCases.ApiCustomerPost@eec5a4a]" name="apiErrorBlankContact" duration-ms="32" started-at="2016-11-01T11:36:52Z" finished-at="2016-11-01T11:36:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- apiErrorBlankContact -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:automationFramework.TestCases.ApiCustomerPost@eec5a4a]" name="setUp" is-config="true" duration-ms="49" started-at="2016-11-01T11:36:52Z" finished-at="2016-11-01T11:36:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="apiErrorBlankContactFirstName()[pri:0, instance:automationFramework.TestCases.ApiCustomerPost@eec5a4a]" name="apiErrorBlankContactFirstName" duration-ms="52" started-at="2016-11-01T11:36:52Z" finished-at="2016-11-01T11:36:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- apiErrorBlankContactFirstName -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:automationFramework.TestCases.ApiCustomerPost@eec5a4a]" name="setUp" is-config="true" duration-ms="21" started-at="2016-11-01T11:36:52Z" finished-at="2016-11-01T11:36:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="apiErrorBlankContactLastName()[pri:0, instance:automationFramework.TestCases.ApiCustomerPost@eec5a4a]" name="apiErrorBlankContactLastName" duration-ms="32" started-at="2016-11-01T11:36:52Z" finished-at="2016-11-01T11:36:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- apiErrorBlankContactLastName -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:automationFramework.TestCases.ApiCustomerPost@eec5a4a]" name="setUp" is-config="true" duration-ms="17" started-at="2016-11-01T11:36:52Z" finished-at="2016-11-01T11:36:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="apiErrorBlankContactName()[pri:0, instance:automationFramework.TestCases.ApiCustomerPost@eec5a4a]" name="apiErrorBlankContactName" duration-ms="36" started-at="2016-11-01T11:36:52Z" finished-at="2016-11-01T11:36:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- apiErrorBlankContactName -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:automationFramework.TestCases.ApiCustomerPost@eec5a4a]" name="setUp" is-config="true" duration-ms="17" started-at="2016-11-01T11:36:52Z" finished-at="2016-11-01T11:36:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="apiErrorBlankContactType()[pri:0, instance:automationFramework.TestCases.ApiCustomerPost@eec5a4a]" name="apiErrorBlankContactType" duration-ms="39" started-at="2016-11-01T11:36:52Z" finished-at="2016-11-01T11:36:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- apiErrorBlankContactType -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:automationFramework.TestCases.ApiCustomerPost@eec5a4a]" name="setUp" is-config="true" duration-ms="26" started-at="2016-11-01T11:36:52Z" finished-at="2016-11-01T11:36:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="apiErrorBlankCountry()[pri:0, instance:automationFramework.TestCases.ApiCustomerPost@eec5a4a]" name="apiErrorBlankCountry" duration-ms="29" started-at="2016-11-01T11:36:52Z" finished-at="2016-11-01T11:36:52Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [If address is provided, country is required.] but found [Field is blank.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [If address is provided, country is required.] but found [Field is blank.]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at automationFramework.TestCases.ApiCustomerPost.checkError(ApiCustomerPost.java:374)
	at automationFramework.TestCases.ApiCustomerPost.apiErrorBlankCountry(ApiCustomerPost.java:255)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:177)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:105)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:103)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:74)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- apiErrorBlankCountry -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:automationFramework.TestCases.ApiCustomerPost@eec5a4a]" name="setUp" is-config="true" duration-ms="15" started-at="2016-11-01T11:36:52Z" finished-at="2016-11-01T11:36:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="apiErrorBlankCustomerType()[pri:0, instance:automationFramework.TestCases.ApiCustomerPost@eec5a4a]" name="apiErrorBlankCustomerType" duration-ms="75" started-at="2016-11-01T11:36:52Z" finished-at="2016-11-01T11:36:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- apiErrorBlankCustomerType -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:automationFramework.TestCases.ApiCustomerPost@eec5a4a]" name="setUp" is-config="true" duration-ms="20" started-at="2016-11-01T11:36:52Z" finished-at="2016-11-01T11:36:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="apiErrorInvalidContactType()[pri:0, instance:automationFramework.TestCases.ApiCustomerPost@eec5a4a]" name="apiErrorInvalidContactType" duration-ms="45" started-at="2016-11-01T11:36:52Z" finished-at="2016-11-01T11:36:52Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Invalid contact type.] but found [Invalid value.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Invalid contact type.] but found [Invalid value.]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at automationFramework.TestCases.ApiCustomerPost.checkError(ApiCustomerPost.java:374)
	at automationFramework.TestCases.ApiCustomerPost.apiErrorInvalidContactType(ApiCustomerPost.java:86)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:177)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:105)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:103)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:74)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- apiErrorInvalidContactType -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:automationFramework.TestCases.ApiCustomerPost@eec5a4a]" name="setUp" is-config="true" duration-ms="15" started-at="2016-11-01T11:36:52Z" finished-at="2016-11-01T11:36:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="apiErrorInvalidCustomerType()[pri:0, instance:automationFramework.TestCases.ApiCustomerPost@eec5a4a]" name="apiErrorInvalidCustomerType" duration-ms="29" started-at="2016-11-01T11:36:53Z" finished-at="2016-11-01T11:36:53Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Invalid customer type.] but found [Invalid value.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Invalid customer type.] but found [Invalid value.]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at automationFramework.TestCases.ApiCustomerPost.checkError(ApiCustomerPost.java:374)
	at automationFramework.TestCases.ApiCustomerPost.apiErrorInvalidCustomerType(ApiCustomerPost.java:65)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:177)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:105)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:103)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:74)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- apiErrorInvalidCustomerType -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:automationFramework.TestCases.ApiCustomerPost@eec5a4a]" name="setUp" is-config="true" duration-ms="15" started-at="2016-11-01T11:36:53Z" finished-at="2016-11-01T11:36:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="apiErrorInvalidSuffixId()[pri:0, instance:automationFramework.TestCases.ApiCustomerPost@eec5a4a]" name="apiErrorInvalidSuffixId" duration-ms="54" started-at="2016-11-01T11:36:53Z" finished-at="2016-11-01T11:36:53Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at automationFramework.TestCases.ApiCustomerPost.checkError(ApiCustomerPost.java:372)
	at automationFramework.TestCases.ApiCustomerPost.apiErrorInvalidSuffixId(ApiCustomerPost.java:176)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:177)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:105)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:103)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:74)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- apiErrorInvalidSuffixId -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:automationFramework.TestCases.ApiCustomerPost@eec5a4a]" name="setUp" is-config="true" duration-ms="11" started-at="2016-11-01T11:36:53Z" finished-at="2016-11-01T11:36:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="apiErrorMaxLengthAddress()[pri:0, instance:automationFramework.TestCases.ApiCustomerPost@eec5a4a]" name="apiErrorMaxLengthAddress" duration-ms="30" started-at="2016-11-01T11:36:53Z" finished-at="2016-11-01T11:36:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- apiErrorMaxLengthAddress -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:automationFramework.TestCases.ApiCustomerPost@eec5a4a]" name="setUp" is-config="true" duration-ms="15" started-at="2016-11-01T11:36:53Z" finished-at="2016-11-01T11:36:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="apiErrorMaxLengthAddress2()[pri:0, instance:automationFramework.TestCases.ApiCustomerPost@eec5a4a]" name="apiErrorMaxLengthAddress2" duration-ms="30" started-at="2016-11-01T11:36:53Z" finished-at="2016-11-01T11:36:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- apiErrorMaxLengthAddress2 -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:automationFramework.TestCases.ApiCustomerPost@eec5a4a]" name="setUp" is-config="true" duration-ms="12" started-at="2016-11-01T11:36:53Z" finished-at="2016-11-01T11:36:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="apiErrorMaxLengthCity()[pri:0, instance:automationFramework.TestCases.ApiCustomerPost@eec5a4a]" name="apiErrorMaxLengthCity" duration-ms="47" started-at="2016-11-01T11:36:53Z" finished-at="2016-11-01T11:36:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- apiErrorMaxLengthCity -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:automationFramework.TestCases.ApiCustomerPost@eec5a4a]" name="setUp" is-config="true" duration-ms="14" started-at="2016-11-01T11:36:53Z" finished-at="2016-11-01T11:36:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="apiErrorMaxLengthContactFirstName()[pri:0, instance:automationFramework.TestCases.ApiCustomerPost@eec5a4a]" name="apiErrorMaxLengthContactFirstName" duration-ms="54" started-at="2016-11-01T11:36:53Z" finished-at="2016-11-01T11:36:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- apiErrorMaxLengthContactFirstName -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:automationFramework.TestCases.ApiCustomerPost@eec5a4a]" name="setUp" is-config="true" duration-ms="15" started-at="2016-11-01T11:36:53Z" finished-at="2016-11-01T11:36:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="apiErrorMaxLengthContactLastName()[pri:0, instance:automationFramework.TestCases.ApiCustomerPost@eec5a4a]" name="apiErrorMaxLengthContactLastName" duration-ms="41" started-at="2016-11-01T11:36:53Z" finished-at="2016-11-01T11:36:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- apiErrorMaxLengthContactLastName -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:automationFramework.TestCases.ApiCustomerPost@eec5a4a]" name="setUp" is-config="true" duration-ms="23" started-at="2016-11-01T11:36:53Z" finished-at="2016-11-01T11:36:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="apiErrorMaxLengthContactMiddleName()[pri:0, instance:automationFramework.TestCases.ApiCustomerPost@eec5a4a]" name="apiErrorMaxLengthContactMiddleName" duration-ms="30" started-at="2016-11-01T11:36:53Z" finished-at="2016-11-01T11:36:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- apiErrorMaxLengthContactMiddleName -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:automationFramework.TestCases.ApiCustomerPost@eec5a4a]" name="setUp" is-config="true" duration-ms="12" started-at="2016-11-01T11:36:53Z" finished-at="2016-11-01T11:36:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="apiPostSuccess()[pri:0, instance:automationFramework.TestCases.ApiCustomerPost@eec5a4a]" name="apiPostSuccess" duration-ms="55" started-at="2016-11-01T11:36:53Z" finished-at="2016-11-01T11:36:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- apiPostSuccess -->
      </class> <!-- automationFramework.TestCases.ApiCustomerPost -->
    </test> <!-- ApiTest -->
  </suite> <!-- Test2 - Suite -->
</testng-results>
