<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="NACTS-081729" name="automationFramework.TestCases.ApiOamLinkSubsystemErrors" tests="16" failures="0" timestamp="10 Oct 2016 22:35:24 GMT" time="3.159" errors="3">
  <testcase name="ApiSubsystemIdMax" time="0.078" classname="automationFramework.TestCases.ApiOamLinkSubsystemErrors">
    <error type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at automationFramework.TestCases.ApiOamLinkSubsystemErrors.sendApiRequest(ApiOamLinkSubsystemErrors.java:183)
	at automationFramework.TestCases.ApiOamLinkSubsystemErrors.ApiSubsystemIdMax(ApiOamLinkSubsystemErrors.java:118)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
    </error>
  </testcase> <!-- ApiSubsystemIdMax -->
  <testcase name="ApiErrorCustomerIDMax" time="0.047" classname="automationFramework.TestCases.ApiOamLinkSubsystemErrors"/>
  <testcase name="ApiExternalSubsystemAccountIdBlank" time="0.047" classname="automationFramework.TestCases.ApiOamLinkSubsystemErrors"/>
  <testcase name="ApiErrorClientRefIdBlank" time="0.063" classname="automationFramework.TestCases.ApiOamLinkSubsystemErrors"/>
  <testcase name="ApiErrorClientRefIdMax" time="0.078" classname="automationFramework.TestCases.ApiOamLinkSubsystemErrors"/>
  <testcase name="ApiExternalRefNbrBlank" time="0.047" classname="automationFramework.TestCases.ApiOamLinkSubsystemErrors"/>
  <testcase name="ApiErrorAccountBlank" time="0.079" classname="automationFramework.TestCases.ApiOamLinkSubsystemErrors"/>
  <testcase name="ApiBalanceTransferSmall" time="0.078" classname="automationFramework.TestCases.ApiOamLinkSubsystemErrors"/>
  <testcase name="ApiExternalRefNbrMax" time="0.047" classname="automationFramework.TestCases.ApiOamLinkSubsystemErrors"/>
  <testcase name="ApiNickNameMax" time="0.047" classname="automationFramework.TestCases.ApiOamLinkSubsystemErrors"/>
  <testcase name="ApiErrorCustomerIDIncorrect" time="0.065" classname="automationFramework.TestCases.ApiOamLinkSubsystemErrors"/>
  <testcase name="ApiErrorCustomerIDBlank" time="0.062" classname="automationFramework.TestCases.ApiOamLinkSubsystemErrors"/>
  <testcase name="ApiErrorAccountNotFound" time="0.047" classname="automationFramework.TestCases.ApiOamLinkSubsystemErrors"/>
  <testcase name="ApiExternalSubsystemAccountIdMax" time="0.062" classname="automationFramework.TestCases.ApiOamLinkSubsystemErrors"/>
  <testcase name="ApiErrorAccountMax" time="0.063" classname="automationFramework.TestCases.ApiOamLinkSubsystemErrors">
    <error type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at automationFramework.TestCases.ApiOamLinkSubsystemErrors.sendApiRequest(ApiOamLinkSubsystemErrors.java:183)
	at automationFramework.TestCases.ApiOamLinkSubsystemErrors.ApiErrorAccountMax(ApiOamLinkSubsystemErrors.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
    </error>
  </testcase> <!-- ApiErrorAccountMax -->
  <testcase name="ApiBalanceTransferLarge" time="2.249" classname="automationFramework.TestCases.ApiOamLinkSubsystemErrors">
    <error type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at automationFramework.TestCases.ApiOamLinkSubsystemErrors.sendApiRequest(ApiOamLinkSubsystemErrors.java:183)
	at automationFramework.TestCases.ApiOamLinkSubsystemErrors.ApiBalanceTransferLarge(ApiOamLinkSubsystemErrors.java:143)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
    </error>
  </testcase> <!-- ApiBalanceTransferLarge -->
</testsuite> <!-- automationFramework.TestCases.ApiOamLinkSubsystemErrors -->
