<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="ApiTest"
           tests="16"
           failures="3"
           errors="0"
           skipped="0"
           time="3.159">
  <properties />
            <testcase name="ApiSubsystemIdMax" time="0.078" classname="automationFramework.TestCases.ApiOamLinkSubsystemErrors">
                <failure type="java.lang.AssertionError"
                  message="expected [true] but found [false]"
              >
<![CDATA[java.lang.AssertionError: expected [true] but found [false]
  org.testng.Assert.fail(Assert.java:94)
  org.testng.Assert.failNotEquals(Assert.java:494)
  org.testng.Assert.assertTrue(Assert.java:42)
  org.testng.Assert.assertTrue(Assert.java:52)
  automationFramework.TestCases.ApiOamLinkSubsystemErrors.sendApiRequest(ApiOamLinkSubsystemErrors.java:183)
  automationFramework.TestCases.ApiOamLinkSubsystemErrors.ApiSubsystemIdMax(ApiOamLinkSubsystemErrors.java:118)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
  org.testng.TestRunner.privateRun(TestRunner.java:767)
  org.testng.TestRunner.run(TestRunner.java:617)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
  org.testng.SuiteRunner.run(SuiteRunner.java:240)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
  org.testng.TestNG.run(TestNG.java:1031)
  org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
  org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
  org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
      </failure>

          </testcase>
            <testcase name="ApiErrorAccountMax" time="0.063" classname="automationFramework.TestCases.ApiOamLinkSubsystemErrors">
                <failure type="java.lang.AssertionError"
                  message="expected [true] but found [false]"
              >
<![CDATA[java.lang.AssertionError: expected [true] but found [false]
  org.testng.Assert.fail(Assert.java:94)
  org.testng.Assert.failNotEquals(Assert.java:494)
  org.testng.Assert.assertTrue(Assert.java:42)
  org.testng.Assert.assertTrue(Assert.java:52)
  automationFramework.TestCases.ApiOamLinkSubsystemErrors.sendApiRequest(ApiOamLinkSubsystemErrors.java:183)
  automationFramework.TestCases.ApiOamLinkSubsystemErrors.ApiErrorAccountMax(ApiOamLinkSubsystemErrors.java:84)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
  org.testng.TestRunner.privateRun(TestRunner.java:767)
  org.testng.TestRunner.run(TestRunner.java:617)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
  org.testng.SuiteRunner.run(SuiteRunner.java:240)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
  org.testng.TestNG.run(TestNG.java:1031)
  org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
  org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
  org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
      </failure>

          </testcase>
            <testcase name="ApiBalanceTransferLarge" time="2.249" classname="automationFramework.TestCases.ApiOamLinkSubsystemErrors">
                <failure type="java.lang.AssertionError"
                  message="expected [true] but found [false]"
              >
<![CDATA[java.lang.AssertionError: expected [true] but found [false]
  org.testng.Assert.fail(Assert.java:94)
  org.testng.Assert.failNotEquals(Assert.java:494)
  org.testng.Assert.assertTrue(Assert.java:42)
  org.testng.Assert.assertTrue(Assert.java:52)
  automationFramework.TestCases.ApiOamLinkSubsystemErrors.sendApiRequest(ApiOamLinkSubsystemErrors.java:183)
  automationFramework.TestCases.ApiOamLinkSubsystemErrors.ApiBalanceTransferLarge(ApiOamLinkSubsystemErrors.java:143)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
  org.testng.TestRunner.privateRun(TestRunner.java:767)
  org.testng.TestRunner.run(TestRunner.java:617)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
  org.testng.SuiteRunner.run(SuiteRunner.java:240)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
  org.testng.TestNG.run(TestNG.java:1031)
  org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
  org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
  org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
      </failure>

          </testcase>
  
  
            <testcase name="ApiErrorCustomerIDMax" time="0.047" classname="automationFramework.TestCases.ApiOamLinkSubsystemErrors" />
                <testcase name="ApiExternalSubsystemAccountIdBlank" time="0.047" classname="automationFramework.TestCases.ApiOamLinkSubsystemErrors" />
                <testcase name="ApiErrorClientRefIdBlank" time="0.063" classname="automationFramework.TestCases.ApiOamLinkSubsystemErrors" />
                <testcase name="ApiErrorClientRefIdMax" time="0.078" classname="automationFramework.TestCases.ApiOamLinkSubsystemErrors" />
                <testcase name="ApiExternalRefNbrBlank" time="0.047" classname="automationFramework.TestCases.ApiOamLinkSubsystemErrors" />
                <testcase name="ApiErrorAccountBlank" time="0.079" classname="automationFramework.TestCases.ApiOamLinkSubsystemErrors" />
                <testcase name="ApiBalanceTransferSmall" time="0.078" classname="automationFramework.TestCases.ApiOamLinkSubsystemErrors" />
                <testcase name="ApiExternalRefNbrMax" time="0.047" classname="automationFramework.TestCases.ApiOamLinkSubsystemErrors" />
                <testcase name="ApiNickNameMax" time="0.047" classname="automationFramework.TestCases.ApiOamLinkSubsystemErrors" />
                <testcase name="ApiErrorCustomerIDIncorrect" time="0.065" classname="automationFramework.TestCases.ApiOamLinkSubsystemErrors" />
                <testcase name="ApiErrorCustomerIDBlank" time="0.062" classname="automationFramework.TestCases.ApiOamLinkSubsystemErrors" />
                <testcase name="ApiErrorAccountNotFound" time="0.047" classname="automationFramework.TestCases.ApiOamLinkSubsystemErrors" />
                <testcase name="ApiExternalSubsystemAccountIdMax" time="0.062" classname="automationFramework.TestCases.ApiOamLinkSubsystemErrors" />
      
</testsuite>
