<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="ApiTest"
           tests="72"
           failures="20"
           errors="0"
           skipped="0"
           time="9.274">
  <properties />
            <testcase name="apiErrorBlankPhoneNumber3" time="0.094" classname="automationFramework.NextWave2RestApi.ApiCustomerPost">
                <failure type="java.lang.AssertionError"
                  message="expected [contact.phone[2].phoneNumber] but found [contact.phone[2].number]"
              >
<![CDATA[java.lang.AssertionError: expected [contact.phone[2].phoneNumber] but found [contact.phone[2].number]
  org.testng.Assert.fail(Assert.java:94)
  org.testng.Assert.failNotEquals(Assert.java:494)
  org.testng.Assert.assertEquals(Assert.java:123)
  org.testng.Assert.assertEquals(Assert.java:176)
  org.testng.Assert.assertEquals(Assert.java:186)
  automationFramework.NextWave2RestApi.ApiCustomerPost.checkError(ApiCustomerPost.java:1019)
  automationFramework.NextWave2RestApi.ApiCustomerPost.apiErrorBlankPhoneNumber3(ApiCustomerPost.java:500)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
  org.testng.TestRunner.privateRun(TestRunner.java:767)
  org.testng.TestRunner.run(TestRunner.java:617)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
  org.testng.SuiteRunner.run(SuiteRunner.java:240)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
  org.testng.TestNG.run(TestNG.java:1031)
  org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
  org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
  org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
      </failure>

          </testcase>
            <testcase name="apiErrorBlankPhoneNumber" time="0.036" classname="automationFramework.NextWave2RestApi.ApiCustomerPost">
                <failure type="java.lang.AssertionError"
                  message="expected [contact.phone[0].phoneNumber] but found [contact.phone[0].number]"
              >
<![CDATA[java.lang.AssertionError: expected [contact.phone[0].phoneNumber] but found [contact.phone[0].number]
  org.testng.Assert.fail(Assert.java:94)
  org.testng.Assert.failNotEquals(Assert.java:494)
  org.testng.Assert.assertEquals(Assert.java:123)
  org.testng.Assert.assertEquals(Assert.java:176)
  org.testng.Assert.assertEquals(Assert.java:186)
  automationFramework.NextWave2RestApi.ApiCustomerPost.checkError(ApiCustomerPost.java:1019)
  automationFramework.NextWave2RestApi.ApiCustomerPost.apiErrorBlankPhoneNumber(ApiCustomerPost.java:420)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
  org.testng.TestRunner.privateRun(TestRunner.java:767)
  org.testng.TestRunner.run(TestRunner.java:617)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
  org.testng.SuiteRunner.run(SuiteRunner.java:240)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
  org.testng.TestNG.run(TestNG.java:1031)
  org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
  org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
  org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
      </failure>

          </testcase>
            <testcase name="apiErrorContainDictionaryPassword" time="0.070" classname="automationFramework.NextWave2RestApi.ApiCustomerPost">
                <failure type="java.lang.NullPointerException"
                  message="(null)"
              >
<![CDATA[java.lang.NullPointerException
  automationFramework.NextWave2RestApi.ApiCustomerPost.checkError(ApiCustomerPost.java:1019)
  automationFramework.NextWave2RestApi.ApiCustomerPost.apiErrorContainDictionaryPassword(ApiCustomerPost.java:773)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
  org.testng.TestRunner.privateRun(TestRunner.java:767)
  org.testng.TestRunner.run(TestRunner.java:617)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
  org.testng.SuiteRunner.run(SuiteRunner.java:240)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
  org.testng.TestNG.run(TestNG.java:1031)
  org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
  org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
  org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
      </failure>

          </testcase>
            <testcase name="apiErrorBlankPhoneType2" time="0.070" classname="automationFramework.NextWave2RestApi.ApiCustomerPost">
                <failure type="java.lang.AssertionError"
                  message="expected [contact.phone[1].phoneType] but found [contact.phone[1].type]"
              >
<![CDATA[java.lang.AssertionError: expected [contact.phone[1].phoneType] but found [contact.phone[1].type]
  org.testng.Assert.fail(Assert.java:94)
  org.testng.Assert.failNotEquals(Assert.java:494)
  org.testng.Assert.assertEquals(Assert.java:123)
  org.testng.Assert.assertEquals(Assert.java:176)
  org.testng.Assert.assertEquals(Assert.java:186)
  automationFramework.NextWave2RestApi.ApiCustomerPost.checkError(ApiCustomerPost.java:1019)
  automationFramework.NextWave2RestApi.ApiCustomerPost.apiErrorBlankPhoneType2(ApiCustomerPost.java:481)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
  org.testng.TestRunner.privateRun(TestRunner.java:767)
  org.testng.TestRunner.run(TestRunner.java:617)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
  org.testng.SuiteRunner.run(SuiteRunner.java:240)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
  org.testng.TestNG.run(TestNG.java:1031)
  org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
  org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
  org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
      </failure>

          </testcase>
            <testcase name="apiErrorContainDigitsPassword" time="0.076" classname="automationFramework.NextWave2RestApi.ApiCustomerPost">
                <failure type="java.lang.NullPointerException"
                  message="(null)"
              >
<![CDATA[java.lang.NullPointerException
  automationFramework.NextWave2RestApi.ApiCustomerPost.checkError(ApiCustomerPost.java:1019)
  automationFramework.NextWave2RestApi.ApiCustomerPost.apiErrorContainDigitsPassword(ApiCustomerPost.java:733)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
  org.testng.TestRunner.privateRun(TestRunner.java:767)
  org.testng.TestRunner.run(TestRunner.java:617)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
  org.testng.SuiteRunner.run(SuiteRunner.java:240)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
  org.testng.TestNG.run(TestNG.java:1031)
  org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
  org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
  org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
      </failure>

          </testcase>
            <testcase name="apiErrorInvalidPhoneType" time="0.037" classname="automationFramework.NextWave2RestApi.ApiCustomerPost">
                <failure type="java.lang.AssertionError"
                  message="expected [contact.phone[0].phoneType] but found [contact.phone[0].type]"
              >
<![CDATA[java.lang.AssertionError: expected [contact.phone[0].phoneType] but found [contact.phone[0].type]
  org.testng.Assert.fail(Assert.java:94)
  org.testng.Assert.failNotEquals(Assert.java:494)
  org.testng.Assert.assertEquals(Assert.java:123)
  org.testng.Assert.assertEquals(Assert.java:176)
  org.testng.Assert.assertEquals(Assert.java:186)
  automationFramework.NextWave2RestApi.ApiCustomerPost.checkError(ApiCustomerPost.java:1019)
  automationFramework.NextWave2RestApi.ApiCustomerPost.apiErrorInvalidPhoneType(ApiCustomerPost.java:450)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
  org.testng.TestRunner.privateRun(TestRunner.java:767)
  org.testng.TestRunner.run(TestRunner.java:617)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
  org.testng.SuiteRunner.run(SuiteRunner.java:240)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
  org.testng.TestNG.run(TestNG.java:1031)
  org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
  org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
  org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
      </failure>

          </testcase>
            <testcase name="apiErrorBlankPhoneType3" time="0.057" classname="automationFramework.NextWave2RestApi.ApiCustomerPost">
                <failure type="java.lang.AssertionError"
                  message="expected [contact.phone[2].phoneType] but found [contact.phone[2].type]"
              >
<![CDATA[java.lang.AssertionError: expected [contact.phone[2].phoneType] but found [contact.phone[2].type]
  org.testng.Assert.fail(Assert.java:94)
  org.testng.Assert.failNotEquals(Assert.java:494)
  org.testng.Assert.assertEquals(Assert.java:123)
  org.testng.Assert.assertEquals(Assert.java:176)
  org.testng.Assert.assertEquals(Assert.java:186)
  automationFramework.NextWave2RestApi.ApiCustomerPost.checkError(ApiCustomerPost.java:1019)
  automationFramework.NextWave2RestApi.ApiCustomerPost.apiErrorBlankPhoneType3(ApiCustomerPost.java:521)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
  org.testng.TestRunner.privateRun(TestRunner.java:767)
  org.testng.TestRunner.run(TestRunner.java:617)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
  org.testng.SuiteRunner.run(SuiteRunner.java:240)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
  org.testng.TestNG.run(TestNG.java:1031)
  org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
  org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
  org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
      </failure>

          </testcase>
            <testcase name="apiErrorMaxLengthPassword" time="0.063" classname="automationFramework.NextWave2RestApi.ApiCustomerPost">
                <failure type="java.lang.NullPointerException"
                  message="(null)"
              >
<![CDATA[java.lang.NullPointerException
  automationFramework.NextWave2RestApi.ApiCustomerPost.checkError(ApiCustomerPost.java:1019)
  automationFramework.NextWave2RestApi.ApiCustomerPost.apiErrorMaxLengthPassword(ApiCustomerPost.java:723)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
  org.testng.TestRunner.privateRun(TestRunner.java:767)
  org.testng.TestRunner.run(TestRunner.java:617)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
  org.testng.SuiteRunner.run(SuiteRunner.java:240)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
  org.testng.TestNG.run(TestNG.java:1031)
  org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
  org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
  org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
      </failure>

          </testcase>
            <testcase name="apiErrorContainContigousCharacterPin" time="0.071" classname="automationFramework.NextWave2RestApi.ApiCustomerPost">
                <failure type="java.lang.NullPointerException"
                  message="(null)"
              >
<![CDATA[java.lang.NullPointerException
  automationFramework.NextWave2RestApi.ApiCustomerPost.checkError(ApiCustomerPost.java:1019)
  automationFramework.NextWave2RestApi.ApiCustomerPost.apiErrorContainContigousCharacterPin(ApiCustomerPost.java:804)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
  org.testng.TestRunner.privateRun(TestRunner.java:767)
  org.testng.TestRunner.run(TestRunner.java:617)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
  org.testng.SuiteRunner.run(SuiteRunner.java:240)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
  org.testng.TestNG.run(TestNG.java:1031)
  org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
  org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
  org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
      </failure>

          </testcase>
            <testcase name="apiErrorContainConsecutiveCharacterPin" time="0.085" classname="automationFramework.NextWave2RestApi.ApiCustomerPost">
                <failure type="java.lang.NullPointerException"
                  message="(null)"
              >
<![CDATA[java.lang.NullPointerException
  automationFramework.NextWave2RestApi.ApiCustomerPost.checkError(ApiCustomerPost.java:1019)
  automationFramework.NextWave2RestApi.ApiCustomerPost.apiErrorContainConsecutiveCharacterPin(ApiCustomerPost.java:794)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
  org.testng.TestRunner.privateRun(TestRunner.java:767)
  org.testng.TestRunner.run(TestRunner.java:617)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
  org.testng.SuiteRunner.run(SuiteRunner.java:240)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
  org.testng.TestNG.run(TestNG.java:1031)
  org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
  org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
  org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
      </failure>

          </testcase>
            <testcase name="apiErrorMixCasesPassword" time="0.070" classname="automationFramework.NextWave2RestApi.ApiCustomerPost">
                <failure type="java.lang.NullPointerException"
                  message="(null)"
              >
<![CDATA[java.lang.NullPointerException
  automationFramework.NextWave2RestApi.ApiCustomerPost.checkError(ApiCustomerPost.java:1019)
  automationFramework.NextWave2RestApi.ApiCustomerPost.apiErrorMixCasesPassword(ApiCustomerPost.java:743)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
  org.testng.TestRunner.privateRun(TestRunner.java:767)
  org.testng.TestRunner.run(TestRunner.java:617)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
  org.testng.SuiteRunner.run(SuiteRunner.java:240)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
  org.testng.TestNG.run(TestNG.java:1031)
  org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
  org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
  org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
      </failure>

          </testcase>
            <testcase name="apiErrorBlankPhoneType" time="0.038" classname="automationFramework.NextWave2RestApi.ApiCustomerPost">
                <failure type="java.lang.AssertionError"
                  message="expected [contact.phone[0].phoneType] but found [contact.phone[0].type]"
              >
<![CDATA[java.lang.AssertionError: expected [contact.phone[0].phoneType] but found [contact.phone[0].type]
  org.testng.Assert.fail(Assert.java:94)
  org.testng.Assert.failNotEquals(Assert.java:494)
  org.testng.Assert.assertEquals(Assert.java:123)
  org.testng.Assert.assertEquals(Assert.java:176)
  org.testng.Assert.assertEquals(Assert.java:186)
  automationFramework.NextWave2RestApi.ApiCustomerPost.checkError(ApiCustomerPost.java:1019)
  automationFramework.NextWave2RestApi.ApiCustomerPost.apiErrorBlankPhoneType(ApiCustomerPost.java:440)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
  org.testng.TestRunner.privateRun(TestRunner.java:767)
  org.testng.TestRunner.run(TestRunner.java:617)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
  org.testng.SuiteRunner.run(SuiteRunner.java:240)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
  org.testng.TestNG.run(TestNG.java:1031)
  org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
  org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
  org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
      </failure>

          </testcase>
            <testcase name="apiErrorInvalidPhoneNumber3" time="0.025" classname="automationFramework.NextWave2RestApi.ApiCustomerPost">
                <failure type="java.lang.AssertionError"
                  message="expected [contact.phone[2].phoneNumber] but found [contact.phone[2].number]"
              >
<![CDATA[java.lang.AssertionError: expected [contact.phone[2].phoneNumber] but found [contact.phone[2].number]
  org.testng.Assert.fail(Assert.java:94)
  org.testng.Assert.failNotEquals(Assert.java:494)
  org.testng.Assert.assertEquals(Assert.java:123)
  org.testng.Assert.assertEquals(Assert.java:176)
  org.testng.Assert.assertEquals(Assert.java:186)
  automationFramework.NextWave2RestApi.ApiCustomerPost.checkError(ApiCustomerPost.java:1019)
  automationFramework.NextWave2RestApi.ApiCustomerPost.apiErrorInvalidPhoneNumber3(ApiCustomerPost.java:510)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
  org.testng.TestRunner.privateRun(TestRunner.java:767)
  org.testng.TestRunner.run(TestRunner.java:617)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
  org.testng.SuiteRunner.run(SuiteRunner.java:240)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
  org.testng.TestNG.run(TestNG.java:1031)
  org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
  org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
  org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
      </failure>

          </testcase>
            <testcase name="apiErrorInvalidPhoneNumber" time="0.026" classname="automationFramework.NextWave2RestApi.ApiCustomerPost">
                <failure type="java.lang.AssertionError"
                  message="expected [contact.phone[0].phoneNumber] but found [contact.phone[0].number]"
              >
<![CDATA[java.lang.AssertionError: expected [contact.phone[0].phoneNumber] but found [contact.phone[0].number]
  org.testng.Assert.fail(Assert.java:94)
  org.testng.Assert.failNotEquals(Assert.java:494)
  org.testng.Assert.assertEquals(Assert.java:123)
  org.testng.Assert.assertEquals(Assert.java:176)
  org.testng.Assert.assertEquals(Assert.java:186)
  automationFramework.NextWave2RestApi.ApiCustomerPost.checkError(ApiCustomerPost.java:1019)
  automationFramework.NextWave2RestApi.ApiCustomerPost.apiErrorInvalidPhoneNumber(ApiCustomerPost.java:430)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
  org.testng.TestRunner.privateRun(TestRunner.java:767)
  org.testng.TestRunner.run(TestRunner.java:617)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
  org.testng.SuiteRunner.run(SuiteRunner.java:240)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
  org.testng.TestNG.run(TestNG.java:1031)
  org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
  org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
  org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
      </failure>

          </testcase>
            <testcase name="apiErrorContainSpecialCharactersPassword" time="0.073" classname="automationFramework.NextWave2RestApi.ApiCustomerPost">
                <failure type="java.lang.NullPointerException"
                  message="(null)"
              >
<![CDATA[java.lang.NullPointerException
  automationFramework.NextWave2RestApi.ApiCustomerPost.checkError(ApiCustomerPost.java:1019)
  automationFramework.NextWave2RestApi.ApiCustomerPost.apiErrorContainSpecialCharactersPassword(ApiCustomerPost.java:763)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
  org.testng.TestRunner.privateRun(TestRunner.java:767)
  org.testng.TestRunner.run(TestRunner.java:617)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
  org.testng.SuiteRunner.run(SuiteRunner.java:240)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
  org.testng.TestNG.run(TestNG.java:1031)
  org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
  org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
  org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
      </failure>

          </testcase>
            <testcase name="apiErrorInvalidPhoneType2" time="0.046" classname="automationFramework.NextWave2RestApi.ApiCustomerPost">
                <failure type="java.lang.AssertionError"
                  message="expected [contact.phone[1].phoneType] but found [contact.phone[1].type]"
              >
<![CDATA[java.lang.AssertionError: expected [contact.phone[1].phoneType] but found [contact.phone[1].type]
  org.testng.Assert.fail(Assert.java:94)
  org.testng.Assert.failNotEquals(Assert.java:494)
  org.testng.Assert.assertEquals(Assert.java:123)
  org.testng.Assert.assertEquals(Assert.java:176)
  org.testng.Assert.assertEquals(Assert.java:186)
  automationFramework.NextWave2RestApi.ApiCustomerPost.checkError(ApiCustomerPost.java:1019)
  automationFramework.NextWave2RestApi.ApiCustomerPost.apiErrorInvalidPhoneType2(ApiCustomerPost.java:491)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
  org.testng.TestRunner.privateRun(TestRunner.java:767)
  org.testng.TestRunner.run(TestRunner.java:617)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
  org.testng.SuiteRunner.run(SuiteRunner.java:240)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
  org.testng.TestNG.run(TestNG.java:1031)
  org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
  org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
  org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
      </failure>

          </testcase>
            <testcase name="apiErrorAddressId" time="1.569" classname="automationFramework.NextWave2RestApi.ApiCustomerPost">
                <failure type="java.lang.NullPointerException"
                  message="(null)"
              >
<![CDATA[java.lang.NullPointerException
  automationFramework.NextWave2RestApi.ApiCustomerPost.checkError(ApiCustomerPost.java:1019)
  automationFramework.NextWave2RestApi.ApiCustomerPost.apiErrorAddressId(ApiCustomerPost.java:297)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
  org.testng.TestRunner.privateRun(TestRunner.java:767)
  org.testng.TestRunner.run(TestRunner.java:617)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
  org.testng.SuiteRunner.run(SuiteRunner.java:240)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
  org.testng.TestNG.run(TestNG.java:1031)
  org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
  org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
  org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
      </failure>

          </testcase>
            <testcase name="apiErrorBlankPhoneNumber2" time="0.054" classname="automationFramework.NextWave2RestApi.ApiCustomerPost">
                <failure type="java.lang.AssertionError"
                  message="expected [contact.phone[1].phoneNumber] but found [contact.phone[1].number]"
              >
<![CDATA[java.lang.AssertionError: expected [contact.phone[1].phoneNumber] but found [contact.phone[1].number]
  org.testng.Assert.fail(Assert.java:94)
  org.testng.Assert.failNotEquals(Assert.java:494)
  org.testng.Assert.assertEquals(Assert.java:123)
  org.testng.Assert.assertEquals(Assert.java:176)
  org.testng.Assert.assertEquals(Assert.java:186)
  automationFramework.NextWave2RestApi.ApiCustomerPost.checkError(ApiCustomerPost.java:1019)
  automationFramework.NextWave2RestApi.ApiCustomerPost.apiErrorBlankPhoneNumber2(ApiCustomerPost.java:460)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
  org.testng.TestRunner.privateRun(TestRunner.java:767)
  org.testng.TestRunner.run(TestRunner.java:617)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
  org.testng.SuiteRunner.run(SuiteRunner.java:240)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
  org.testng.TestNG.run(TestNG.java:1031)
  org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
  org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
  org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
      </failure>

          </testcase>
            <testcase name="apiErrorInvalidPhoneNumber2" time="0.071" classname="automationFramework.NextWave2RestApi.ApiCustomerPost">
                <failure type="java.lang.AssertionError"
                  message="expected [contact.phone[1].phoneNumber] but found [contact.phone[1].number]"
              >
<![CDATA[java.lang.AssertionError: expected [contact.phone[1].phoneNumber] but found [contact.phone[1].number]
  org.testng.Assert.fail(Assert.java:94)
  org.testng.Assert.failNotEquals(Assert.java:494)
  org.testng.Assert.assertEquals(Assert.java:123)
  org.testng.Assert.assertEquals(Assert.java:176)
  org.testng.Assert.assertEquals(Assert.java:186)
  automationFramework.NextWave2RestApi.ApiCustomerPost.checkError(ApiCustomerPost.java:1019)
  automationFramework.NextWave2RestApi.ApiCustomerPost.apiErrorInvalidPhoneNumber2(ApiCustomerPost.java:470)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
  org.testng.TestRunner.privateRun(TestRunner.java:767)
  org.testng.TestRunner.run(TestRunner.java:617)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
  org.testng.SuiteRunner.run(SuiteRunner.java:240)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
  org.testng.TestNG.run(TestNG.java:1031)
  org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
  org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
  org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
      </failure>

          </testcase>
            <testcase name="apiErrorInvalidPhoneType3" time="0.081" classname="automationFramework.NextWave2RestApi.ApiCustomerPost">
                <failure type="java.lang.AssertionError"
                  message="expected [contact.phone[2].phoneType] but found [contact.phone[2].type]"
              >
<![CDATA[java.lang.AssertionError: expected [contact.phone[2].phoneType] but found [contact.phone[2].type]
  org.testng.Assert.fail(Assert.java:94)
  org.testng.Assert.failNotEquals(Assert.java:494)
  org.testng.Assert.assertEquals(Assert.java:123)
  org.testng.Assert.assertEquals(Assert.java:176)
  org.testng.Assert.assertEquals(Assert.java:186)
  automationFramework.NextWave2RestApi.ApiCustomerPost.checkError(ApiCustomerPost.java:1019)
  automationFramework.NextWave2RestApi.ApiCustomerPost.apiErrorInvalidPhoneType3(ApiCustomerPost.java:532)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
  org.testng.TestRunner.privateRun(TestRunner.java:767)
  org.testng.TestRunner.run(TestRunner.java:617)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
  org.testng.SuiteRunner.run(SuiteRunner.java:240)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
  org.testng.TestNG.run(TestNG.java:1031)
  org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
  org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
  org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
      </failure>

          </testcase>
  
  
            <testcase name="apiErrorMaxLengthCity" time="0.047" classname="automationFramework.NextWave2RestApi.ApiCustomerPost" />
                <testcase name="apiErrorMaxLengthPersonalId" time="0.033" classname="automationFramework.NextWave2RestApi.ApiCustomerPost" />
                <testcase name="apiErrorMaxLengthAddress2" time="0.052" classname="automationFramework.NextWave2RestApi.ApiCustomerPost" />
                <testcase name="apiErrorBlankContactLastName" time="0.052" classname="automationFramework.NextWave2RestApi.ApiCustomerPost" />
                <testcase name="apiErrorBlankUserName" time="0.041" classname="automationFramework.NextWave2RestApi.ApiCustomerPost" />
                <testcase name="apiErrorTooLongPin" time="0.048" classname="automationFramework.NextWave2RestApi.ApiCustomerPost" />
                <testcase name="apiErrorInvalidPersonalIdType" time="0.039" classname="automationFramework.NextWave2RestApi.ApiCustomerPost" />
                <testcase name="apiErrorInvalidUserName" time="0.116" classname="automationFramework.NextWave2RestApi.ApiCustomerPost" />
                <testcase name="apiErrorBlankPersonalIdType" time="0.054" classname="automationFramework.NextWave2RestApi.ApiCustomerPost" />
                <testcase name="apiErrorContainConsecutiveCharacterPassword" time="1.250" classname="automationFramework.NextWave2RestApi.ApiCustomerPost" />
                <testcase name="apiErrorContainUsernamePassword" time="0.035" classname="automationFramework.NextWave2RestApi.ApiCustomerPost" />
                <testcase name="apiGetCustomerInfo" time="0.240" classname="automationFramework.NextWave2RestApi.ApiCustomerPost" />
                <testcase name="apiErrorInvalidCustomerType" time="0.036" classname="automationFramework.NextWave2RestApi.ApiCustomerPost" />
                <testcase name="apiErrorBlankContactFirstName" time="0.060" classname="automationFramework.NextWave2RestApi.ApiCustomerPost" />
                <testcase name="apiErrorInvalidPostalCode" time="0.066" classname="automationFramework.NextWave2RestApi.ApiCustomerPost" />
                <testcase name="apiErrorSecurityQuestionInvalid" time="0.042" classname="automationFramework.NextWave2RestApi.ApiCustomerPost" />
                <testcase name="apiErrorInvalidState" time="0.032" classname="automationFramework.NextWave2RestApi.ApiCustomerPost" />
                <testcase name="apiErrorInvalidSuffixId" time="0.038" classname="automationFramework.NextWave2RestApi.ApiCustomerPost" />
                <testcase name="apiErrorDuplicateUserName" time="0.134" classname="automationFramework.NextWave2RestApi.ApiCustomerPost" />
                <testcase name="apiErrorMaxLengthUserName" time="0.103" classname="automationFramework.NextWave2RestApi.ApiCustomerPost" />
                <testcase name="apiErrorInvalidCountry" time="0.030" classname="automationFramework.NextWave2RestApi.ApiCustomerPost" />
                <testcase name="apiErrorBlankAddress" time="1.073" classname="automationFramework.NextWave2RestApi.ApiCustomerPost" />
                <testcase name="apiErrorTooSmallPin" time="0.042" classname="automationFramework.NextWave2RestApi.ApiCustomerPost" />
                <testcase name="apiPostSuccess" time="0.069" classname="automationFramework.NextWave2RestApi.ApiCustomerPost" />
                <testcase name="apiErrorMaxLengthContactFirstName" time="0.037" classname="automationFramework.NextWave2RestApi.ApiCustomerPost" />
                <testcase name="apiErrorSpecialCharactersUserName" time="0.027" classname="automationFramework.NextWave2RestApi.ApiCustomerPost" />
                <testcase name="apiErrorInvalidFormatEmail" time="0.043" classname="automationFramework.NextWave2RestApi.ApiCustomerPost" />
                <testcase name="apiErrorBlankContactName" time="0.333" classname="automationFramework.NextWave2RestApi.ApiCustomerPost" />
                <testcase name="apiGetSuccess" time="0.028" classname="automationFramework.NextWave2RestApi.ApiCustomerPost" />
                <testcase name="apiErrorBlankContactType" time="0.064" classname="automationFramework.NextWave2RestApi.ApiCustomerPost" />
                <testcase name="apiErrorBlankPersonalId" time="0.077" classname="automationFramework.NextWave2RestApi.ApiCustomerPost" />
                <testcase name="apiErrorMaxLengthContactLastName" time="0.031" classname="automationFramework.NextWave2RestApi.ApiCustomerPost" />
                <testcase name="apiErrorContainUsernamePin" time="0.042" classname="automationFramework.NextWave2RestApi.ApiCustomerPost" />
                <testcase name="apiErrorSpecialCharactersEmail" time="0.031" classname="automationFramework.NextWave2RestApi.ApiCustomerPost" />
                <testcase name="apiErrorMustContainLettersPassword" time="0.055" classname="automationFramework.NextWave2RestApi.ApiCustomerPost" />
                <testcase name="apiErrorBlankState" time="0.079" classname="automationFramework.NextWave2RestApi.ApiCustomerPost" />
                <testcase name="apiErrorBlankCity" time="0.064" classname="automationFramework.NextWave2RestApi.ApiCustomerPost" />
                <testcase name="apiErrorBlankPassword" time="0.044" classname="automationFramework.NextWave2RestApi.ApiCustomerPost" />
                <testcase name="apiErrorBlankContact" time="0.056" classname="automationFramework.NextWave2RestApi.ApiCustomerPost" />
                <testcase name="apiErrorMaximumLengthEmail" time="0.040" classname="automationFramework.NextWave2RestApi.ApiCustomerPost" />
                <testcase name="apiErrorBlankCustomerType" time="0.038" classname="automationFramework.NextWave2RestApi.ApiCustomerPost" />
                <testcase name="apiErrorBlankPostalCode" time="0.035" classname="automationFramework.NextWave2RestApi.ApiCustomerPost" />
                <testcase name="apiErrorMaxLengthAddress" time="0.031" classname="automationFramework.NextWave2RestApi.ApiCustomerPost" />
                <testcase name="apiErrorSecurityQuestionBlank" time="0.044" classname="automationFramework.NextWave2RestApi.ApiCustomerPost" />
                <testcase name="apiErrorMinLengthPassword" time="0.042" classname="automationFramework.NextWave2RestApi.ApiCustomerPost" />
                <testcase name="apiErrorMaxLengthContactMiddleName" time="0.034" classname="automationFramework.NextWave2RestApi.ApiCustomerPost" />
                <testcase name="apiErrorNonNumericPin" time="0.060" classname="automationFramework.NextWave2RestApi.ApiCustomerPost" />
                <testcase name="apiErrorSecurityAnswerBlank" time="0.033" classname="automationFramework.NextWave2RestApi.ApiCustomerPost" />
                <testcase name="apiErrorBlankCountry" time="0.044" classname="automationFramework.NextWave2RestApi.ApiCustomerPost" />
                <testcase name="apiErrorBlankEmail" time="0.095" classname="automationFramework.NextWave2RestApi.ApiCustomerPost" />
                <testcase name="apiErrorSecurityAnswerMaxLength" time="1.268" classname="automationFramework.NextWave2RestApi.ApiCustomerPost" />
                <testcase name="apiErrorInvalidContactType" time="0.055" classname="automationFramework.NextWave2RestApi.ApiCustomerPost" />
      
</testsuite>
